# docker-compose.yml
version: '3.8'

services:
  app:
    build: 
      context: ./pcforge
    volumes:
      - ./pcforge:/pcforge
    ports:
      - "8000:8000"
    depends_on:
      - db
      # - nginx
    command: gunicorn --workers 3 --bind 0.0.0.0:8000 PCForge.wsgi:application
    #command: python manage.py runserver 0.0.0.0:8000

  db:
    image: postgres:13
    volumes:
      #- postgres_data:/var/lib/postgresql/data
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ProyectoTFG
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 20042001

  nginx:
    restart: always
    image: nginx:alpine
    volumes:
    - ./pcforge/core/static:/static
    - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "10000:80"
    depends_on:
      - app
      
