# Generated by Django 5.0.6 on 2024-06-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_estadisticasschema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estadisticas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitas', models.PositiveIntegerField(default=0)),
                ('peticiones', models.PositiveIntegerField(default=0)),
                ('guardadas', models.PositiveIntegerField(default=0)),
                ('facturas', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='EstadisticasSchema',
        ),
    ]
