# Generated by Django 5.0.6 on 2024-06-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_estadisticas_delete_estadisticasschema'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadisticas',
            name='edicion',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadisticas',
            name='gama_alta',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadisticas',
            name='gama_baja',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadisticas',
            name='gama_media',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadisticas',
            name='gaming',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadisticas',
            name='ia',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadisticas',
            name='ofimatica',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
