# Generated by Django 5.0.6 on 2024-06-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_estadisticas_edicion_estadisticas_gama_alta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('country', models.CharField(choices=[('US', 'US'), ('CA', 'CA'), ('EU', 'EU')], max_length=2)),
                ('phone_number', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('agree_to_policies', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
